services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    image: ghcr.io/lamourmathys/saone-local:api
    env_file:
      - ./server/.env
    volumes:
      - shared_uploads:/app/uploads
    depends_on:
      - db

  app:
    image: ghcr.io/lamourmathys/saone-local:app
    environment:
      - API_URL=http://api:3000
      - PORT=3001
    volumes:
      - shared_uploads:/app/public/uploads
    depends_on:
      - api

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - shared_uploads:/var/www/uploads:ro
    depends_on:
      - app
      - api

volumes:
  postgres_data:
  shared_uploads: