name: CI

on: [push, pull_request]

jobs:
  check-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Vérifier le README
        run: test -f readme.md

      - name: Vérifier les .txt
        run: find . -name "*.txt" | grep .
